<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CNAMTS\PHPK\CoreBundle\Data\Repository;

/**
 * EmmaEnvoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
//class EmmaEnvoiRepository extends \Doctrine\ORM\EntityRepository
class EmmaEnvoiRepository extends EntityRepository implements Repository
{
	public function liste(){
		return null;
	}
	
	public function InsertNbCourriers($nb){
		
		$connexion = $this->getEntityManager()->getConnection();

        $sql = "insert into emma_envoi (date_envoi, type_envoi, appli, nb) values(sysdate, 'courrier', '3202', ".$nb.")";

        $statement = $connexion->query($sql);
        return $statement;
	}

	public function InsertNbCSV($nb){
		
		$connexion = $this->getEntityManager()->getConnection();

        $sql = "insert into emma_envoi (date_envoi, type_envoi, appli, nb) values(sysdate, 'csv', '3202', ".$nb.")";

        $statement = $connexion->query($sql);
        return $statement;
	}

	public function getDatesEnvoiCSV(){
		
		$connexion = $this->getEntityManager()->getConnection();

        $sql = "SELECT DISTINCT TRUNC(DATE_ENVOI, 'J') as DATE_ENVOI FROM EMMA_ENVOI WHERE TYPE_ENVOI = 'csv' ORDER BY DATE_ENVOI DESC";

        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}

	public function deleteEnvoi($bdd, $date_envoi){
		
		$connexion = $this->getEntityManager()->getConnection();

        $sql = "DELETE FROM ".$bdd." WHERE TYPE_ENVOI = 'csv' AND APPLI='3202' AND TRUNC(DATE_ENVOI, 'J') = TO_DATE('".$date_envoi."', 'DD/MM/YYYY')";

        $statement = $connexion->query($sql);
        return $statement;
	}

		public function deleteCSV($bdd, $date_envoi){
		
		$connexion = $this->getEntityManager()->getConnection();

        $sql = "DELETE FROM ".$bdd." WHERE TRUNC(DATE_ENVOI, 'J') = TO_DATE('".$date_envoi."', 'DD/MM/YYYY')";

        $statement = $connexion->query($sql);
        return $statement;
	}

}
