<?php

namespace AppBundle\Repository;

/**
 * emma_assureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class emma_assureRepository extends \Doctrine\ORM\EntityRepository
{
}
