<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CNAMTS\PHPK\CoreBundle\Data\Repository;
/**
 * Prn3202Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
//class Prn3202Repository extends \Doctrine\ORM\EntityRepository
class Prn3202Repository extends EntityRepository implements Repository
{	
	public function liste(){
		return null;
	}
	public function update_apres_courrier($nir){
		$connexion = $this->getEntityManager()->getConnection();

		//$query="UPDATE prn_3202 set date_envoi=sysdate where nir='".$nir."' and date_envoi is null and deleted is null AND DATE_RECUP >= next_day(trunc(sysdate), 'MONDAY') - 14 and DATE_RECUP < next_day(trunc(sysdate), 'MONDAY') - 7";
        $query="update prn_3202 set date_envoi=sysdate where nir='".$nir."' and date_envoi is null and deleted is null";
        $statement = $connexion->query($query);
		return $statement->execute();

	}
}